cabal-version: 3.14
name: starset
version: 0.1.0
license: MIT
license-file: LICENSE
author: RubenVerg
maintainer: me@rubenverg.com
build-type: Simple

library
  ghc-options: -Wall
  default-language: GHC2024
  hs-source-dirs: src
  exposed-modules: StarSet.Card.Set
                 , StarSet.Game
                 , StarSet.Games
                 , StarSet.Games.NearSet
                 , StarSet.Games.ProSet
                 , StarSet.Games.Set
                 , StarSet.Games.SuperSet
                 , StarSet.Message
                 , StarSet.Play
  build-depends: base
               , miso
               , text
               , containers ^>=0.7
               , combinatorial ^>=0.1.1

executable starset-client
  ghc-options: -Wall
  default-language: GHC2024
  hs-source-dirs: client
  main-is: Main.hs
  build-depends: base
               , starset
               , miso
               , text
               , containers
               , random ^>=1.3.1
               , time ^>=1.14
  if arch(wasm32)
    ghc-options:
      -no-hs-main
      -optl-mexec-model=reactor
      "-optl-Wl,--export=hs_start"
    cpp-options:
      -DWASM

executable starset-server
  ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N
  default-language: GHC2024
  hs-source-dirs: server
  main-is: Main.hs
  build-depends: base
               , starset
               , servant-server ^>=0.20.3.0
               , wai
               , http-types
               , warp
               , wai-app-static
               , servant-websockets ^>=2.0.0
               , websockets
               , text
               , stm ^>=2.5.3.1
               , mtl
               , containers
               , NanoID ^>=3.4.1.2
               , mwc-random
               , vector
               , miso
               , time
